In [1]:
library(dplyr)
library(qqman)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




For example usage please run: vignette('qqman')



Citation appreciated but not required:

Turner, (2018). qqman: an R package for visualizing GWAS results using Q-Q and manhattan plots. Journal of Open Source Software, 3(25), 731, https://doi.org/10.21105/joss.00731.

## Read Data

In [5]:
ham_meta <- read.table("../output/meta_results1.tbl", header = T)

## Format Data

In [8]:
#begin by transforming the p-valu
head(ham_meta)
ham_meta$log10_p_val <- -log10(ham_meta$P.value)

  MarkerName  Allele1 Allele2 Freq1  FreqSE MinFreq MaxFreq Effect  StdErr
1 1:101602673 t       c       0.2086 0      0.2086  0.2086  -0.0434 0.1610
2 3:38936166  a       g       0.1312 0      0.1312  0.1312  -0.1258 0.1879
3 4:88799734  t       c       0.5525 0      0.5525  0.5525  -0.1331 0.1264
4 12:87302710 a       g       0.9889 0      0.9889  0.9889   0.1304 0.5713
5 21:21652866 t       c       0.9420 0      0.9420  0.9420   0.2534 0.2635
6 5:130079592 t       c       0.0124 0      0.0124  0.0124  -1.1684 0.6112
  P.value Direction
1 0.78750 ?-
2 0.50320 ?-
3 0.29240 ?-
4 0.81950 ?+
5 0.33610 ?+
6 0.05593 ?-

In [9]:
 colnames(ham_meta) <- c("SNP", "A1","A2","FREQ_A1", "FREQ_A1_SE",
                        "MIN_FREQ_A1", "MAX_FREQ_A1", "BETA", "SE",
                         "P", "DIRECTION", "LOG10_P")

In [27]:
# Split the SNP name
snp_split <- strsplit(ham_meta$SNP, split = ':')

# Save chromosome and position
ham_meta$CHR <- unlist(lapply(snp_split, function(x){x[1]})) |> as.numeric()
ham_meta$BP <- unlist(lapply(snp_split, function(x){x[2]})) |> as.numeric()

In [28]:
#unlist(lapply(t, function(x){x[1]}))
head(ham_meta)

  SNP         A1 A2 FREQ_A1 FREQ_A1_SE MIN_FREQ_A1 MAX_FREQ_A1 BETA    SE
1 1:101602673 t  c  0.2086  0          0.2086      0.2086      -0.0434 0.1610
2 3:38936166  a  g  0.1312  0          0.1312      0.1312      -0.1258 0.1879
3 4:88799734  t  c  0.5525  0          0.5525      0.5525      -0.1331 0.1264
4 12:87302710 a  g  0.9889  0          0.9889      0.9889       0.1304 0.5713
5 21:21652866 t  c  0.9420  0          0.9420      0.9420       0.2534 0.2635
6 5:130079592 t  c  0.0124  0          0.0124      0.0124      -1.1684 0.6112
  P       DIRECTION LOG10_P    CHR BP
1 0.78750 ?-        0.10374944  1  101602673
2 0.50320 ?-        0.29825937  3   38936166
3 0.29240 ?-        0.53402263  4   88799734
4 0.81950 ?+        0.08645104 12   87302710
5 0.33610 ?+        0.47353149 21   21652866
6 0.05593 ?-        1.25235518  5  130079592

## Make Plots

In [29]:
png("../output/meta_ham_manhattan.png")
manhattan(ham_meta, ylim = c(0, 8), 
    col = c("BROWN3", "DEEPSKYBLUE3","DARKOLIVEGREEN3","MEDIUMPURPLE"))
dev.off()

png
  2

In [30]:
png("../output/ham_qq_regenie.png")
qq(ham_meta$P,xlim = c(0, 8), ylim = c(0, 8))
dev.off()

png
  2

## Format Sum Stats to Save

In [31]:
write.table(ham_meta,"../output/meta_ham_ss.txt", row.names = F, col.names = T, quote = F)

Check the significant hits

In [32]:
ham_meta |> filter(P < 5e-8)

  SNP         A1 A2 FREQ_A1 FREQ_A1_SE MIN_FREQ_A1 MAX_FREQ_A1 BETA    SE
1 6:31164308  t  c  0.2391  0.3467     0.0713      0.9558      -0.7554 0.1370
2 1:159077922 a  g  0.8163  0.0000     0.8163      0.8163      -0.9534 0.1745
3 1:159070185 a  c  0.1761  0.0000     0.1761      0.1761       1.0031 0.1813
4 6:30946974  t  c  0.7539  0.3615     0.0407      0.9371       0.8318 0.1463
  P         DIRECTION LOG10_P  CHR BP
1 3.524e-08 --        7.452964 6    31164308
2 4.679e-08 ?-        7.329847 1   159077922
3 3.122e-08 ?+        7.505567 1   159070185
4 1.295e-08 ++        7.887730 6    30946974